name: Angular CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Grant execute permissions to ng
        run: chmod +x ./node_modules/.bin/ng

      - name: Build
        run: npm run build:prod

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist/mpa/browser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
